---
label: default
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: textarea
  name: description
  label: Description
  description: A short description of the page
  config:
    required: true
- type: textarea
  name: body
  label: Body
  config:
    wysiwyg: true
    schema:
      format: markdown
- type: text
  name: layout
  label: layout
  hidden: true
  default: post
pages:
- calendar.md
